### ISSUE TITLE
Support for .ts files?

### ISSUE THREAD

**Issue by gossi** [candidmetrics/ember-module-snippets#2]
I love this extension. Since I'm switching over to typescript, I realized, this ext doesn't work on `.ts` files. Can you make it work with them as well?

**Comment by averydev** [comment]
Sure can!

**Comment by averydev** [comment]
Just published that change! Thanks for the heads up :)

**Comment by gossi** [comment]
Meanwhile I realized, Typescript is capable of just typing `isBlank` either in the "header" of the file or within code and then hitting ctrl + space will actually place the import statement to the top.

**Comment by averydev** [comment]
What the heck!  I don't even think that has to do with typescript, it works in js too... Is it figuring out that it can import from the `npm_modules` somehow?
