### ISSUE TITLE
Autocomplete issue

### ISSUE THREAD

**Issue by ludalex** [candidmetrics/ember-module-snippets#3]
![autocomplete](https://user-images.githubusercontent.com/1538479/37518894-6223cec2-2917-11e8-8dd4-d80232595739.gif)

When you type "E" then add a dot to fire this library autocompletes, now VSCode autocompletes in Element. this preventing to use it like intended.

**Comment by averydev** [comment]
Hi there @ludalex yeah this has been an unpleasant change. 
I'm thinking that perhaps changing the hotkeys to `e.` rather than `E.` is a reasonable alternative. 

Any other ideas?

**Comment by davelowensohn** [comment]
Is ‘em.’ taken? Seems more future-proof.

**Comment by averydev** [comment]
Yeah, `em.` makes sense to me

**Comment by davelowensohn** [comment]
Just took a crack at this. @averydev - can you give #4 a look & confirm it does what it's supposed to?

**Comment by averydev** [comment]
Well, this isn't particularly awesome. It looks like the dot may be reserved in some fashion (now?)
![not great](https://user-images.githubusercontent.com/477027/37564112-6572c084-2a4c-11e8-8ce2-09302940d3e6.gif)
`em.` seems to have the same issues as `E.` The underlying problem it seems with `E.` is the dot, not the E.

I was just trying out some different options for the trigger, and I think my favorite is 
`E[space]`
which I think would be pretty unlikely to get trampled on by another extension. 
Thoughts?

**Comment by averydev** [comment]
Actually there's a problem with that too, which is that if you delete up to the space, it stops recognizing the snippet invocations. 
I have a new favorite which is `E:` It looks better in list form, and deleting up to the prefix doesn't cause problems. 
![screencast 2018-03-18 01-49-13](https://user-images.githubusercontent.com/477027/37564234-cdeb174a-2a4e-11e8-821b-83b6a92e48c2.gif)

**Comment by davelowensohn** [comment]
Yeesh. That sounds like the best option - from an ergonomics standpoint you’ll already have your finger on the shift key, and if VS Code core somehow comes for ‘E:’ I’ll see you back in Atom.

**Comment by averydev** [comment]
Resolved in 1.0 build!
Also added E:super in 1.1
